name: '贝莱德世界科技基金净值查询'
on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 2 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: '获取服务器时间'
        run: echo "服务器时间:$(date +'%Y-%m-%dT%H:%M:%S')"
      - name: '拉取代码'
        uses: actions/checkout@v2
      - name: '初始化Python环境'
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: '安装依赖'
        run: python -m pip install --upgrade pip
      - name: '开始执行脚本'
        env:
          SKEY: ${{ secrets.SKEY }}
        run: |
          pip install requests
          pip install beautifulsoup4
          python3 blackrock.py