name: 爱奇艺签到
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: 10 2  * * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
      - name: 初始化Python环境
      - uses: actions/checkout@master
      
      - name: 安装依赖并替换环境变量
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
        env:
          SKEY: ${{ secrets.SKEY }}
          P00001: ${{ secrets.P00001 }}
        run: |
          pip install -r requirements.txt
          python3 iqiyi.py
