name: 爱奇艺签到
on:
  push:
    branches: [master]
  schedule:
    - cron: '0 10 1 ? * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 获取仓库代码
        uses: actions/checkout@master
      - name: 初始化Python环境
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: 安装依赖
        run: pip install -r requirements.txt
      - name: 开始签到
        env:
          SKEY: ${{ secrets.SKEY }}
          P00001: ${{ secrets.P00001 }}
        run: python3 iqiyi.py
